#!/bin/bash

# ------------------------------------------------------------------------------
# Install PM2.
#
# PM2 is a process manager for Node.js applications.  It provides an easy way to
# daemonise Node.js apps - so they can be run in the background as a service and
# automatically started on server boot.
#
# https://pm2.io/
# ------------------------------------------------------------------------------

npm install -g pm2

# The follow command generates an init script for Ubuntu's "systemd" init system
# and sets the init script to be run automatically as the "adm_*" user on server
# bootup. Thus, applications must be started (eg: "pm start path/to/app.js") and
# saved ("pm2 save") as the same "adm_*" user, if you want those applications to
# run automatically.
#
# The following command is generated by running:
#
#   $ pm2 startup systemd -u ${adm_user} --hp /home/${adm_user}
#
sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ${adm_user} --hp /home/${adm_user}

# Now, to check the status of the process unit:
#
#   $ systemctl status pm2-${adm_user}
#

# Install the "pm2-logrotate" plugin, to automatically rotate log files - saving
# disk space. https://github.com/keymetrics/pm2-logrotate
pm2 install pm2-logrotate

# Configure PM2 log rotation. Start a fresh log file every day (at 1am), or when
# the file size reaches 1 megabyte, whichever comes sooner. Archive the previous
# log file and keep no more tan 10 past log files.
pm2 set pm2-logrotate:rotateInterval '0 1 * * *'
pm2 set pm2-logrotate:max_size 1M
pm2 set pm2-logrotate:retain 10
pm2 set pm2-logrotate:compress true
